environment:
  matrix:
     - GENERATOR: "Visual Studio 14"
       CONFIG: Debug
     - GENERATOR: "Visual Studio 14"
       CONFIG: Release

build_script:
  - python build_system/appveyor.helper.py

matrix:
  fast_finish: true
